source "https://supermarket.chef.io"

metadata

cookbook 'mysql', '~> 6.0.22'
cookbook 'apache2', '~> 3.0.1'
cookbook 'php', '~> 1.5.0'
cookbook 'apt', '~> 2.7.0'
cookbook 'lampp', path: '/Users/Patrik/Documents/workspace/csm_ss15_sem_team_vagrant/lamp-apache/chef/project_cookbooks/lampp'